// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPOYjIQv_BmTPghcjHHXsT7ZrLbD9TzJM',
    appId: '1:981519690346:web:c37fdac614e991b63a3813',
    messagingSenderId: '981519690346',
    projectId: 'noteapp-43e44',
    authDomain: 'noteapp-43e44.firebaseapp.com',
    storageBucket: 'noteapp-43e44.firebasestorage.app',
    measurementId: 'G-7EM32GPYB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmNe2pUI8Rq0QtUc2r-7byqChDaAY-JvU',
    appId: '1:981519690346:android:55b1c5f6970498483a3813',
    messagingSenderId: '981519690346',
    projectId: 'noteapp-43e44',
    storageBucket: 'noteapp-43e44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cMFa2qWpZIRMRd6U5P7PqwwoIEU7EjM',
    appId: '1:981519690346:ios:db33dc89567c3fb13a3813',
    messagingSenderId: '981519690346',
    projectId: 'noteapp-43e44',
    storageBucket: 'noteapp-43e44.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2cMFa2qWpZIRMRd6U5P7PqwwoIEU7EjM',
    appId: '1:981519690346:ios:db33dc89567c3fb13a3813',
    messagingSenderId: '981519690346',
    projectId: 'noteapp-43e44',
    storageBucket: 'noteapp-43e44.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPOYjIQv_BmTPghcjHHXsT7ZrLbD9TzJM',
    appId: '1:981519690346:web:2cea9d104d5b65603a3813',
    messagingSenderId: '981519690346',
    projectId: 'noteapp-43e44',
    authDomain: 'noteapp-43e44.firebaseapp.com',
    storageBucket: 'noteapp-43e44.firebasestorage.app',
    measurementId: 'G-SXNGP063BE',
  );
}
